### ISSUE TITLE
undefined symbol: mvm, rkf_float

### ISSUE THREAD

**Issue by joncox123** [agb32/dasp#3]
Due to changes in GCC, functions declared 'incline' will not be compiled properly by GCC. With Ubuntu 18.04, for example, I receive the error below. The solution is to add the 'static' keyword before the declaration of all 'inline' functions.

'static' must be added to mvm() and rk_float() in scrnmodule.c, iscrnmodule.c and centmodule.c

> python scao.py --iterations=200
Traceback (most recent call last):
  File "scao.py", line 28, in <module>
    import science.infScrn
  File "/home/joncox/git/dasp/science/infScrn.py", line 103, in <module>
    import cmod.scrn
ImportError: /home/joncox/git/dasp/cmod/scrnmodule.so: undefined symbol: mvm

**Comment by agb32** [comment]
Thanks - have made the changes.

**Comment by joncox123** [comment]
I think this was fixed. I was able to compile the latest branch.

**Comment by maximecharriere** [comment]
A static is missing here :
https://github.com/agb32/dasp/blob/master/cmod/src/centmodule.c#L973
